ALTER TABLE "Restaurant"
ADD COLUMN "stripeAccountId" TEXT,
ADD COLUMN "stripeAccountStatus" TEXT NOT NULL DEFAULT 'DISCONNECTED',
ADD COLUMN "stripeChargesEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "stripePayoutsEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "stripeDetailsSubmitted" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "platformFeeBps" INTEGER NOT NULL DEFAULT 0;
