import { MenuSection } from "@/lib/types"

const VAT = 0.175

const COFFEE_ADD_ONS = [
  {
    name: "syrup (vanilla, caramel, hazelnut, coconut)",
    priceDelta: 0.5,
  },
  {
    name: "alternative milk (oat, almond, soya, coconut)",
    priceDelta: 0.5,
  },
  {
    name: "whipping cream / marshmallow",
    priceDelta: 0.5,
  },
  {
    name: "collagen",
    priceDelta: 1,
  },
]

const GLASS_TO_BOTTLE = (glass: number, bottle: number) => ({
  name: "bottle",
  priceDelta: Number((bottle - glass).toFixed(2)),
})

export const DEFAULT_MENU: MenuSection[] = [
  {
    id: "breakfast-brunch",
    name: "Breakfast/Brunch",
    items: [
      {
        id: "toasted-sourdough-jam-butter",
        name: "Toasted sourdough with jam and butter",
        description: "Toasted sourdough with jam and butter.",
        image: null,
        basePrice: 2.5,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
      {
        id: "toasted-sourdough-fried-eggs-bacon",
        name: "Toasted sourdough with fried eggs, bacon and brown sauce",
        description: "Toasted sourdough with fried eggs, bacon and brown sauce.",
        image: null,
        basePrice: 11,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
      {
        id: "homemade-sourdough-avocado-egg",
        name: "Homemade sourdough bread, smashed avocado, poached/scrambled egg",
        description: "Smoked salmon available as an add-on.",
        image: null,
        basePrice: 11,
        vatRate: VAT,
        allergens: [],
        editableOptions: {
          swaps: [{ from: "poached egg", to: "scrambled egg" }],
          addOns: [{ name: "smoked salmon", priceDelta: 3 }],
        },
        station: "KITCHEN",
      },
      {
        id: "shakshuka",
        name: "Shakshuka",
        description:
          "With tomatoes, pepper, cumin, onion and garlic, egg and feta, parsley.",
        image: null,
        basePrice: 12.5,
        vatRate: VAT,
        allergens: [],
        editableOptions: {
          addOns: [{ name: "sucuk", priceDelta: 3 }],
        },
        station: "KITCHEN",
      },
      {
        id: "pancakes-berries-banana",
        name: "Pancakes with mixed berries and banana",
        description: "Served with chocolate sauce or maple syrup.",
        image: null,
        basePrice: 12.5,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
      {
        id: "granola-berries-greek-yogurt",
        name: "Granola with mixed nuts, fresh berries, chia seeds, greek yogurt",
        description: "DF option: coconut yogurt.",
        image: null,
        basePrice: 9,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
      {
        id: "french-toast-berries-chocolate",
        name: "French toast with mixed berries and chocolate sauce",
        description: "French toast with mixed berries and chocolate sauce.",
        image: null,
        basePrice: 11,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
      {
        id: "omelette-any-3-fillings",
        name: "Omelette with any 3 fillings",
        description:
          "Fillings: spinach, mushrooms, onion, tomato, chilli, ham, cheese or smoked salmon.",
        image: null,
        basePrice: 12,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
      {
        id: "eggs-florentine",
        name: "Eggs Florentine",
        description: "Smoked salmon available as an add-on.",
        image: null,
        basePrice: 12,
        vatRate: VAT,
        allergens: [],
        editableOptions: {
          addOns: [{ name: "smoked salmon", priceDelta: 3 }],
        },
        station: "KITCHEN",
      },
      {
        id: "charred-grilled-steak-eggs",
        name: "Charred grilled steak and eggs",
        description: "Charred grilled steak and eggs.",
        image: null,
        basePrice: 15,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
    ],
  },
  {
    id: "mains",
    name: "Mains",
    items: [
      {
        id: "signature-grill-wagyu-ribeye-200g",
        name: "Signature Grill: Australian wagyu rib-eye steak, 200g",
        description:
          "Choice of side: broccoli, mac and cheese, or chips. Choice of sauce: peppercorn, truffle mayo, or chimichurri.",
        image: null,
        basePrice: 34,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
      {
        id: "signature-grill-black-angus-sirloin-260-280g",
        name: "Signature Grill: Black Angus sirloin steak, 260-280g",
        description:
          "Choice of side: broccoli, mac and cheese, or chips. Choice of sauce: peppercorn, truffle mayo, or chimichurri.",
        image: null,
        basePrice: 32,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
      {
        id: "signature-grill-lamb-chops-4pcs",
        name: "Signature Grill: Lamb chops on the bone (4 pcs)",
        description:
          "Choice of side: broccoli, mac and cheese, or chips. Choice of sauce: peppercorn, truffle mayo, or chimichurri.",
        image: null,
        basePrice: 24.5,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
      {
        id: "soup-of-the-day",
        name: "Soup of the day served with bread",
        description: "Soup of the day served with bread.",
        image: null,
        basePrice: 6.95,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
      {
        id: "tagliatelle-oyster-mushrooms-black-truffle",
        name: "Tagliatelle with oyster mushrooms and black truffle",
        description: "In a creamy sauce.",
        image: null,
        basePrice: 19,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
      {
        id: "traditional-spaghetti-carbonara",
        name: "Traditional spaghetti carbonara",
        description: "Traditional spaghetti carbonara.",
        image: null,
        basePrice: 17,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
      {
        id: "traditional-rigatonne-beef-bolognese",
        name: "Traditional Rigatonne beef Bolognese",
        description: "Traditional Rigatonne beef Bolognese.",
        image: null,
        basePrice: 17,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
      {
        id: "penne-arrabiata",
        name: "Penne Arrabiata",
        description: "King prawns available as an optional add-on.",
        image: null,
        basePrice: 13,
        vatRate: VAT,
        allergens: [],
        editableOptions: {
          addOns: [{ name: "king prawns", priceDelta: 7 }],
        },
        station: "KITCHEN",
      },
      {
        id: "steak-beef-burger-180g",
        name: "Steak Beef burger 180g",
        description: "With homemade sauce, pickles, and chips.",
        image: null,
        basePrice: 15,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
      {
        id: "panko-breaded-chicken-escalope",
        name: "Panko breaded chicken escalope",
        description: "Served with parmesan fries and mixed salad.",
        image: null,
        basePrice: 15,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
      {
        id: "cesare-salad",
        name: "Cesare Salad",
        description: "Cesare Salad.",
        image: null,
        basePrice: 15,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
      {
        id: "steak-baguette",
        name: "Steak Baguette",
        description:
          "With caramelised onions, rocket, parmesan, mustard. Chips available as an add-on.",
        image: null,
        basePrice: 9,
        vatRate: VAT,
        allergens: [],
        editableOptions: {
          addOns: [{ name: "chips", priceDelta: 4 }],
        },
        station: "KITCHEN",
      },
      {
        id: "breaded-fish-fillets",
        name: "Breaded fish fillets",
        description: "With potato wedges and homemade tartar sauce.",
        image: null,
        basePrice: 16,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
      {
        id: "chicken-breast-creamy-mushroom-sauce",
        name: "Chicken breast in creamy mushroom sauce",
        description: "Served with roast potatoes and vegetables.",
        image: null,
        basePrice: 15,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
    ],
  },
  {
    id: "traditional-pizzas",
    name: "Traditional Pizzas",
    items: [
      {
        id: "margherita-d-o-p",
        name: "Margherita D.O.P.",
        description:
          "Italian tomato sauce, Mozzarella D.O.P., fresh basil, extra virgin olive oil.",
        image: null,
        basePrice: 10,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
      {
        id: "mascarpone-and-speck",
        name: "Mascarpone and Speck",
        description:
          "Italian tomato sauce, Mozzarella, Nduja, Mascarpone D.O.P, speck.",
        image: null,
        basePrice: 15,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
      {
        id: "tartufo-nero",
        name: "Tartufo Nero",
        description:
          "Mozzarella, beef bresaola, truffle pate, chestnut mushrooms, parmigiano shavings.",
        image: null,
        basePrice: 16,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
      {
        id: "parmigiana",
        name: "Parmigiana",
        description:
          "Italian tomato sauce, aubergine and Mozzarella cheese, parmigiano, basil.",
        image: null,
        basePrice: 16,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
      {
        id: "mortadella-e-pistacchio",
        name: "Mortadella e Pistacchio",
        description:
          "Crema di pistacchio, Mozzarella cheese, Mortadella, Buratta, Pistacchio shavings.",
        image: null,
        basePrice: 19,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
      {
        id: "ortolana",
        name: "Ortolana",
        description:
          "Italian tomato sauce, Mozzarella, chestnut mushrooms, spinach, artichoke, habanero.",
        image: null,
        basePrice: 15.5,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
      {
        id: "pepperoni-classico",
        name: "Pepperoni Classico",
        description:
          "Italian tomato sauce, Mozzarella, spicy pepperoni, oregano.",
        image: null,
        basePrice: 14,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
      {
        id: "prosciutto-funghi",
        name: "Prosciutto Funghi",
        description:
          "Italian tomato sauce, Mozzarella, Prosciutto, chestnut mushroom.",
        image: null,
        basePrice: 15.5,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
      {
        id: "nettuno",
        name: "Nettuno",
        description:
          "Italian tomato sauce, Mozzarella, Tuna, olives and red onion.",
        image: null,
        basePrice: 14,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
      {
        id: "pollo-fusion",
        name: "Pollo Fusion",
        description:
          "Italian tomato sauce, Mozzarella, fried chicken, sun-dried tomatoes, roasted peppers, basil and olive oil.",
        image: null,
        basePrice: 15,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
    ],
  },
  {
    id: "desserts",
    name: "Desserts",
    items: [
      {
        id: "chocolate-fondant-with-vanilla-ice-cream",
        name: "Chocolate Fondant with vanilla ice cream",
        description: "Chocolate Fondant with vanilla ice cream.",
        image: null,
        basePrice: 8,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
      {
        id: "brownie-with-vanilla-ice-cream",
        name: "Brownie with vanilla ice cream",
        description: "Brownie with vanilla ice cream.",
        image: null,
        basePrice: 8,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
    ],
  },
  {
    id: "kids-menu",
    name: "Kids menu",
    items: [
      {
        id: "kids-penne-rich-tomato-sauce",
        name: "Penne with rich tomato sauce",
        description: "Penne with rich tomato sauce.",
        image: null,
        basePrice: 7,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
      {
        id: "kids-margherita-san-marzano",
        name: "Margherita",
        description: "San Marzano tomato sauce, mozzarella, fresh basil.",
        image: null,
        basePrice: 7,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
      {
        id: "kids-crispy-chicken-schnitzel",
        name: "Crispy chicken Schnitzel with chips",
        description: "Crispy chicken Schnitzel served with chips.",
        image: null,
        basePrice: 8,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
      {
        id: "kids-beef-cheeseburger",
        name: "Beef cheeseburger served with chips",
        description: "Beef cheeseburger served with chips.",
        image: null,
        basePrice: 8,
        vatRate: VAT,
        allergens: [],
        station: "KITCHEN",
      },
    ],
  },
  {
    id: "coffee-matcha",
    name: "Coffee/Matcha",
    items: [
      {
        id: "espresso",
        name: "Espresso",
        description: "Espresso.",
        image: null,
        basePrice: 2.95,
        vatRate: VAT,
        allergens: [],
        editableOptions: { addOns: COFFEE_ADD_ONS },
        station: "BAR",
      },
      {
        id: "macchiato",
        name: "Macchiato",
        description: "Macchiato.",
        image: null,
        basePrice: 3.2,
        vatRate: VAT,
        allergens: [],
        editableOptions: { addOns: COFFEE_ADD_ONS },
        station: "BAR",
      },
      {
        id: "americano",
        name: "Americano",
        description: "Americano.",
        image: null,
        basePrice: 3.4,
        vatRate: VAT,
        allergens: [],
        editableOptions: { addOns: COFFEE_ADD_ONS },
        station: "BAR",
      },
      {
        id: "cortado",
        name: "Cortado",
        description: "Cortado.",
        image: null,
        basePrice: 3.8,
        vatRate: VAT,
        allergens: [],
        editableOptions: { addOns: COFFEE_ADD_ONS },
        station: "BAR",
      },
      {
        id: "latte-hot-iced",
        name: "Latte Hot/Iced",
        description: "Latte served hot or iced.",
        image: null,
        basePrice: 3.8,
        vatRate: VAT,
        allergens: [],
        editableOptions: {
          swaps: [{ from: "hot", to: "iced" }],
          addOns: COFFEE_ADD_ONS,
        },
        station: "BAR",
      },
      {
        id: "matcha-latte-hot-iced",
        name: "Matcha Latte Hot/Iced",
        description: "Matcha latte with peach, blueberry, or turmeric.",
        image: null,
        basePrice: 4.5,
        vatRate: VAT,
        allergens: [],
        editableOptions: {
          swaps: [
            { from: "hot", to: "iced" },
            { from: "classic", to: "peach" },
            { from: "classic", to: "blueberry" },
            { from: "classic", to: "turmeric" },
          ],
          addOns: COFFEE_ADD_ONS,
        },
        station: "BAR",
      },
      {
        id: "chai-latte-hot-iced",
        name: "Chai Latte Hot/Iced",
        description: "Chai latte served hot or iced.",
        image: null,
        basePrice: 4.2,
        vatRate: VAT,
        allergens: [],
        editableOptions: {
          swaps: [{ from: "hot", to: "iced" }],
          addOns: COFFEE_ADD_ONS,
        },
        station: "BAR",
      },
      {
        id: "cappuccino",
        name: "Cappuccino",
        description: "Cappuccino.",
        image: null,
        basePrice: 3.8,
        vatRate: VAT,
        allergens: [],
        editableOptions: { addOns: COFFEE_ADD_ONS },
        station: "BAR",
      },
      {
        id: "flat-white",
        name: "Flat White",
        description: "Flat White.",
        image: null,
        basePrice: 3.7,
        vatRate: VAT,
        allergens: [],
        editableOptions: { addOns: COFFEE_ADD_ONS },
        station: "BAR",
      },
      {
        id: "mocha",
        name: "Mocha",
        description: "Mocha.",
        image: null,
        basePrice: 4.2,
        vatRate: VAT,
        allergens: [],
        editableOptions: { addOns: COFFEE_ADD_ONS },
        station: "BAR",
      },
      {
        id: "hot-chocolate",
        name: "Hot Chocolate",
        description: "Hot Chocolate.",
        image: null,
        basePrice: 3.5,
        vatRate: VAT,
        allergens: [],
        editableOptions: { addOns: COFFEE_ADD_ONS },
        station: "BAR",
      },
    ],
  },
  {
    id: "fine-loose-teas",
    name: "Fine Loose Teas",
    items: [
      {
        id: "english-breakfast-gold-decaf-earl-grey",
        name: "English Breakfast Gold/ Decaf / Earl Grey",
        description: "Fine loose tea.",
        image: null,
        basePrice: 3.8,
        vatRate: VAT,
        allergens: [],
        station: "BAR",
      },
      {
        id: "chamomile-organic",
        name: "Chamomile Organic",
        description: "Fine loose tea.",
        image: null,
        basePrice: 3.8,
        vatRate: VAT,
        allergens: [],
        station: "BAR",
      },
      {
        id: "fog-green-organic",
        name: "Fog Green Organic",
        description: "Fine loose tea.",
        image: null,
        basePrice: 3.8,
        vatRate: VAT,
        allergens: [],
        station: "BAR",
      },
      {
        id: "jasmine-chung-hao",
        name: "Jasmine Chung Hao",
        description: "Fine loose tea.",
        image: null,
        basePrice: 3.8,
        vatRate: VAT,
        allergens: [],
        station: "BAR",
      },
      {
        id: "lemon-ginger-rooibos",
        name: "Lemon and Ginger Rooibos",
        description: "Fine loose tea.",
        image: null,
        basePrice: 3.8,
        vatRate: VAT,
        allergens: [],
        station: "BAR",
      },
      {
        id: "fresh-mint-tea",
        name: "Fresh Mint Tea",
        description: "Fine loose tea.",
        image: null,
        basePrice: 3.4,
        vatRate: VAT,
        allergens: [],
        station: "BAR",
      },
    ],
  },
  {
    id: "smoothies",
    name: "Smoothies",
    items: [
      {
        id: "super-green",
        name: "Super Green",
        description: "Apple, Spinach, Avocado, Spirulina.",
        image: null,
        basePrice: 6.2,
        vatRate: VAT,
        allergens: [],
        station: "BAR",
      },
      {
        id: "berry-burst",
        name: "Berry Burst",
        description:
          "Strawberry, Blueberry, Raspberry, Banana, Chia seeds.",
        image: null,
        basePrice: 6,
        vatRate: VAT,
        allergens: [],
        station: "BAR",
      },
      {
        id: "detox",
        name: "Detox",
        description:
          "Pineapple, Kiwi, Banana, Celery, Mango, Ginger.",
        image: null,
        basePrice: 6,
        vatRate: VAT,
        allergens: [],
        station: "BAR",
      },
      {
        id: "sunrise-smoothie",
        name: "Sunrise Smoothie",
        description: "Mango, Pineapple, Strawberry.",
        image: null,
        basePrice: 5.9,
        vatRate: VAT,
        allergens: [],
        station: "BAR",
      },
    ],
  },
  {
    id: "alcoholic-drinks",
    name: "Alcoholic Drinks",
    items: [
      {
        id: "sauvignon-blanc-steve-bird",
        name: "Sauvignon Blanc, Steve Bird",
        description: "Malbourough, New Zealand. 175ml/btl.",
        image: null,
        basePrice: 8,
        vatRate: VAT,
        allergens: [],
        editableOptions: {
          addOns: [GLASS_TO_BOTTLE(8, 28)],
        },
        station: "BAR",
      },
      {
        id: "gavi-di-gavi-docg-marchese-luca-spinola",
        name: "Gavi di Gavi, DOCG, Marchese Luca Spinola",
        description: "Italy, Organic. 175ml/btl.",
        image: null,
        basePrice: 9,
        vatRate: VAT,
        allergens: [],
        editableOptions: {
          addOns: [GLASS_TO_BOTTLE(9, 29)],
        },
        station: "BAR",
      },
      {
        id: "sangiovese-guerrieri-colli-pesaresi",
        name: "Sangiovese Guerrieri Colli Pesaresi",
        description: "Marche, Italy.",
        image: null,
        basePrice: 7.5,
        vatRate: VAT,
        allergens: [],
        editableOptions: {
          addOns: [GLASS_TO_BOTTLE(7.5, 27)],
        },
        station: "BAR",
      },
      {
        id: "malbec-1300-uco-valley",
        name: "Malbec '1300', Uco Valley",
        description: "Mendoza, Argentina.",
        image: null,
        basePrice: 8.5,
        vatRate: VAT,
        allergens: [],
        editableOptions: {
          addOns: [GLASS_TO_BOTTLE(8.5, 29)],
        },
        station: "BAR",
      },
      {
        id: "rose-gold-cotes-de-provence",
        name: "Rose Gold, Cotes de Provence, AOP",
        description: "France.",
        image: null,
        basePrice: 9.5,
        vatRate: VAT,
        allergens: [],
        editableOptions: {
          addOns: [GLASS_TO_BOTTLE(9.5, 32)],
        },
        station: "BAR",
      },
      {
        id: "prosecco-brut-rose-doc-luna-argenta",
        name: "Prosecco Brut Rose, DOC, Luna Argenta",
        description: "Italy. 125ml/btl.",
        image: null,
        basePrice: 7.5,
        vatRate: VAT,
        allergens: [],
        editableOptions: {
          addOns: [GLASS_TO_BOTTLE(7.5, 32)],
        },
        station: "BAR",
      },
      {
        id: "prosecco-brut-doc-luna-argenta",
        name: "Prosecco Brut, DOC, Luna Argenta",
        description: "Italy. 125ml/btl.",
        image: null,
        basePrice: 7.5,
        vatRate: VAT,
        allergens: [],
        editableOptions: {
          addOns: [GLASS_TO_BOTTLE(7.5, 32)],
        },
        station: "BAR",
      },
      {
        id: "aperol-spritz",
        name: "Aperol Spritz",
        description: "Aperol, Prosecco, topped with Soda.",
        image: null,
        basePrice: 9,
        vatRate: VAT,
        allergens: [],
        station: "BAR",
      },
      {
        id: "campari-spritz",
        name: "Campari Spritz",
        description: "Campari, Prosecco, topped with Soda.",
        image: null,
        basePrice: 9,
        vatRate: VAT,
        allergens: [],
        station: "BAR",
      },
      {
        id: "bombay-sapphire-gin-and-tonic",
        name: "Bombay Sapphire Gin and Tonic",
        description: "Bombay Sapphire Gin and Tonic.",
        image: null,
        basePrice: 9.5,
        vatRate: VAT,
        allergens: [],
        station: "BAR",
      },
    ],
  },
  {
    id: "beer-cider",
    name: "Beer and Cider",
    items: [
      {
        id: "moretti-zero",
        name: "Moretti 0%",
        description: "330ml.",
        image: null,
        basePrice: 4,
        vatRate: VAT,
        allergens: [],
        station: "BAR",
      },
      {
        id: "camden-hells",
        name: "Camden Hells",
        description: "330ml.",
        image: null,
        basePrice: 5,
        vatRate: VAT,
        allergens: [],
        station: "BAR",
      },
      {
        id: "pillars-helles",
        name: "Pillars Helles",
        description: "330ml.",
        image: null,
        basePrice: 6,
        vatRate: VAT,
        allergens: [],
        station: "BAR",
      },
      {
        id: "pillars-original-pale",
        name: "Pillars Original Pale",
        description: "330ml.",
        image: null,
        basePrice: 6,
        vatRate: VAT,
        allergens: [],
        station: "BAR",
      },
      {
        id: "pillars-pilsner",
        name: "Pillars Pilsner",
        description: "330ml.",
        image: null,
        basePrice: 6,
        vatRate: VAT,
        allergens: [],
        station: "BAR",
      },
      {
        id: "modelo-especial-mexico",
        name: "Modelo Especial (Mexico)",
        description: "330ml.",
        image: null,
        basePrice: 6,
        vatRate: VAT,
        allergens: [],
        station: "BAR",
      },
      {
        id: "galipette-cider-rose",
        name: "Galipette Cider Rose",
        description: "330ml.",
        image: null,
        basePrice: 6,
        vatRate: VAT,
        allergens: [],
        station: "BAR",
      },
      {
        id: "galipette-organic-biologique",
        name: "Galipette Organic Biologique",
        description: "330ml.",
        image: null,
        basePrice: 6,
        vatRate: VAT,
        allergens: [],
        station: "BAR",
      },
    ],
  },
]
